#  ███████████           ████                      ████            █████
# ░░███░░░░░███         ░░███                     ░░███           ░░███
#  ░███    ░███  ██████  ░███  █████ ████  ███████ ░███   ██████  ███████
#  ░██████████  ███░░███ ░███ ░░███ ░███  ███░░███ ░███  ███░░███░░░███░
#  ░███░░░░░░  ░███ ░███ ░███  ░███ ░███ ░███ ░███ ░███ ░███ ░███  ░███
#  ░███        ░███ ░███ ░███  ░███ ░███ ░███ ░███ ░███ ░███ ░███  ░███ ███
#  █████       ░░██████  █████ ░░███████ ░░███████ █████░░██████   ░░█████
# ░░░░░         ░░░░░░  ░░░░░   ░░░░░███  ░░░░░███░░░░░  ░░░░░░     ░░░░░
#                               ███ ░███  ███ ░███
#                              ░░██████  ░░██████
#                               ░░░░░░    ░░░░░░


# Support: https://erosmari.com/discord
# Documentation: https://github.com/soystargaze/Polyglot
# Version: 1.0.0

# Plugin settings
# Language of the plugin
language: "es_es"

settings:
  # Async settings
  async_thread_pool_size: 4 # Quantity of threads used for async tasks

deepl:
  api_key: "TU_CLAVE_AQUI"
  api_url: "https://api-free.deepl.com/v2/translate"
  language_default: "en"